"""
macOS pasteboard bridge and synthetic Cmd+C / Cmd+V for Fixelect.

  * snapshot()/restore() keep EVERY pasteboard item and type, so an image,
    rich text or a file the user had copied survives a fix (the old code saved
    the *selection* after Cmd+C and "restored" that, losing the real clipboard).
  * Our temporary text is tagged org.nspasteboard.TransientType/ConcealedType,
    the convention clipboard managers (Maccy, Raycast, Alfred...) honour.
  * wait_for_modifiers() stops Cmd+C being sent while ⌥/⌃ are still held.
"""

import subprocess
import sys
import time

_has_appkit = False
_has_quartz = False
if sys.platform == "darwin":
    try:
        from AppKit import NSPasteboard, NSPasteboardItem, NSPasteboardTypeString
        _has_appkit = True
    except Exception:
        pass
    try:
        import Quartz
        _has_quartz = True
    except Exception:
        pass

TRANSIENT_TYPES = ("org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
                   "org.nspasteboard.AutoGeneratedType")
_KEY_C, _KEY_V = 8, 9


def _pb():
    return NSPasteboard.generalPasteboard()


def change_count() -> int:
    if _has_appkit:
        try:
            return int(_pb().changeCount())
        except Exception:
            pass
    return -1


def get_text():
    if _has_appkit:
        try:
            s = _pb().stringForType_(NSPasteboardTypeString)
            return None if s is None else str(s)
        except Exception:
            pass
    try:
        return subprocess.run(["pbpaste"], capture_output=True, text=True, timeout=1.0).stdout
    except Exception:
        return None


def set_text(text: str, transient: bool = True) -> bool:
    if _has_appkit:
        try:
            pb = _pb()
            pb.clearContents()
            pb.setString_forType_(text, NSPasteboardTypeString)
            if transient:
                for t in TRANSIENT_TYPES:
                    pb.setString_forType_("", t)
            return True
        except Exception:
            pass
    try:
        p = subprocess.Popen(["pbcopy"], stdin=subprocess.PIPE, text=True)
        p.communicate(input=text, timeout=1.0)
        return p.returncode == 0
    except Exception:
        return False


def snapshot():
    """Every item/type on the pasteboard as [{type: NSData}], [] if empty, None if unavailable."""
    if not _has_appkit:
        text = get_text()
        return None if text is None else [{"__text__": text}]
    try:
        items = []
        for item in _pb().pasteboardItems() or []:
            entry = {}
            for t in item.types() or []:
                data = item.dataForType_(t)
                if data is not None:
                    entry[str(t)] = data
            if entry:
                items.append(entry)
        return items
    except Exception:
        return None


def restore(items, transient: bool = True) -> bool:
    if items is None:
        return False
    if not _has_appkit:
        return set_text(items[0].get("__text__", "") if items else "", transient=False)
    try:
        pb = _pb()
        pb.clearContents()
        objs = []
        for entry in items:
            it = NSPasteboardItem.alloc().init()
            for t, data in entry.items():
                it.setData_forType_(data, t)
            objs.append(it)
        if objs:
            pb.writeObjects_(objs)
        return True
    except Exception:
        return False


def _modifiers_down() -> bool:
    if not _has_quartz:
        return False
    try:
        flags = Quartz.CGEventSourceFlagsState(Quartz.kCGEventSourceStateHIDSystemState)
        mask = (Quartz.kCGEventFlagMaskCommand | Quartz.kCGEventFlagMaskAlternate
                | Quartz.kCGEventFlagMaskControl | Quartz.kCGEventFlagMaskShift)
        return bool(flags & mask)
    except Exception:
        return False


def wait_for_modifiers(timeout: float = 0.5) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline and _modifiers_down():
        time.sleep(0.01)


def simulate_cmd_key(char: str) -> None:
    code = _KEY_C if char.lower() == "c" else _KEY_V
    if _has_quartz:
        try:
            src = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateCombinedSessionState)
            down = Quartz.CGEventCreateKeyboardEvent(src, code, True)
            Quartz.CGEventSetFlags(down, Quartz.kCGEventFlagMaskCommand)
            up = Quartz.CGEventCreateKeyboardEvent(src, code, False)
            Quartz.CGEventSetFlags(up, Quartz.kCGEventFlagMaskCommand)
            Quartz.CGEventPost(Quartz.kCGHIDEventTap, down)
            time.sleep(0.012)
            Quartz.CGEventPost(Quartz.kCGHIDEventTap, up)
            return
        except Exception:
            pass
    try:
        from pynput.keyboard import Controller, Key
        kb = Controller()
        with kb.pressed(Key.cmd):
            kb.press(char)
            kb.release(char)
    except Exception:
        subprocess.run(["osascript", "-e",
                        f'tell application "System Events" to keystroke "{char}" using command down'],
                       capture_output=True, timeout=1.5)


def copy_selection(timeout: float = 0.8) -> bool:
    """Cmd+C and wait for the pasteboard to change. False means nothing was selected."""
    before = change_count()
    simulate_cmd_key("c")
    deadline = time.time() + timeout
    while time.time() < deadline:
        time.sleep(0.015)
        if change_count() != before:
            time.sleep(0.02)
            return True
    return before == -1 and bool(get_text())


def paste() -> None:
    simulate_cmd_key("v")


# Backwards-compatible helpers used by older callers.
def get_clipboard() -> str:
    return get_text() or ""


def set_clipboard(text: str) -> bool:
    return set_text(text, transient=False)
