"""
macOS pasteboard bridge and synthetic Cmd+C / Cmd+V for Fixelect.

  * snapshot()/restore() keep EVERY pasteboard item and type, so an image,
    rich text or a file the user had copied survives a fix (the old code saved
    the *selection* after Cmd+C and "restored" that, losing the real clipboard).
  * Our temporary text is tagged org.nspasteboard.TransientType/ConcealedType,
    the convention clipboard managers (Maccy, Raycast, Alfred...) honour.
  * wait_for_modifiers() stops Cmd+C being sent while ⌥/⌃ are still held.
"""

import subprocess
import sys
import time

_has_appkit = False
_has_quartz = False
if sys.platform == "darwin":
    try:
        from AppKit import NSPasteboard, NSPasteboardItem, NSPasteboardTypeString
        _has_appkit = True
    except Exception:
        pass
    try:
        import Quartz
        _has_quartz = True
    except Exception:
        pass

TRANSIENT_TYPES = ("org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
                   "org.nspasteboard.AutoGeneratedType")
_KEY_C, _KEY_V, _KEY_Z = 8, 9, 6


def _pb():
    return NSPasteboard.generalPasteboard()


def change_count() -> int:
    if _has_appkit:
        try:
            return int(_pb().changeCount())
        except Exception:
            pass
    return -1


def get_text():
    if _has_appkit:
        try:
            s = _pb().stringForType_(NSPasteboardTypeString)
            return None if s is None else str(s)
        except Exception:
            pass
    try:
        return subprocess.run(["pbpaste"], capture_output=True, text=True, timeout=1.0).stdout
    except Exception:
        return None


def get_rich():
    """The rich versions of what was just copied: {"html": str, "rtf": NSData}."""
    out = {}
    if not _has_appkit:
        return out
    try:
        pb = _pb()
        html = pb.stringForType_("public.html")
        if html:
            out["html"] = str(html)
        rtf = pb.dataForType_("public.rtf")
        if rtf is not None and rtf.length():
            out["rtf"] = rtf
    except Exception:
        pass
    return out


def rewrite_rich(rich, old, new):
    """Apply the word edits old -> new to the copied HTML / RTF, keeping formatting.
    Returns {"html": str, "rtf": NSData} with whatever could be mapped safely."""
    import richtext
    out = {}
    if rich.get("html"):
        try:
            html = richtext.rewrite_html(rich["html"], old, new)
            if html is not None:
                out["html"] = html
        except Exception:
            pass
    if rich.get("rtf") is not None:
        try:
            from AppKit import NSAttributedString
            attr, _attrs = NSAttributedString.alloc().initWithRTF_documentAttributes_(rich["rtf"], None)
            if attr is not None:
                m = attr.mutableCopy()
                target = str(m.string())
                spans = richtext.map_spans(target, old, new)
                if spans is not None:
                    for s, e, repl in reversed(spans):
                        us, ue = richtext.utf16_offset(target, s), richtext.utf16_offset(target, e)
                        m.replaceCharactersInRange_withString_((us, ue - us), repl)
                    data = m.RTFFromRange_documentAttributes_((0, m.length()), {})
                    if data is not None:
                        out["rtf"] = data
        except Exception:
            pass
    return out


def set_text(text: str, transient: bool = True, html=None, rtf=None) -> bool:
    if _has_appkit:
        try:
            pb = _pb()
            pb.clearContents()
            pb.setString_forType_(text, NSPasteboardTypeString)
            if html:
                pb.setString_forType_(html, "public.html")
            if rtf is not None:
                pb.setData_forType_(rtf, "public.rtf")
            if transient:
                for t in TRANSIENT_TYPES:
                    pb.setString_forType_("", t)
            return True
        except Exception:
            pass
    try:
        p = subprocess.Popen(["pbcopy"], stdin=subprocess.PIPE, text=True)
        p.communicate(input=text, timeout=1.0)
        return p.returncode == 0
    except Exception:
        return False


def snapshot():
    """Every item/type on the pasteboard as [{type: NSData}], [] if empty, None if unavailable."""
    if not _has_appkit:
        text = get_text()
        return None if text is None else [{"__text__": text}]
    try:
        items = []
        for item in _pb().pasteboardItems() or []:
            entry = {}
            for t in item.types() or []:
                data = item.dataForType_(t)
                if data is not None:
                    entry[str(t)] = data
            if entry:
                items.append(entry)
        return items
    except Exception:
        return None


def restore(items, transient: bool = True) -> bool:
    if items is None:
        return False
    if not _has_appkit:
        return set_text(items[0].get("__text__", "") if items else "", transient=False)
    try:
        pb = _pb()
        pb.clearContents()
        objs = []
        for entry in items:
            it = NSPasteboardItem.alloc().init()
            for t, data in entry.items():
                it.setData_forType_(data, t)
            objs.append(it)
        if objs:
            pb.writeObjects_(objs)
        return True
    except Exception:
        return False


def _modifiers_down() -> bool:
    if not _has_quartz:
        return False
    try:
        flags = Quartz.CGEventSourceFlagsState(Quartz.kCGEventSourceStateHIDSystemState)
        mask = (Quartz.kCGEventFlagMaskCommand | Quartz.kCGEventFlagMaskAlternate
                | Quartz.kCGEventFlagMaskControl | Quartz.kCGEventFlagMaskShift)
        return bool(flags & mask)
    except Exception:
        return False


def wait_for_modifiers(timeout: float = 0.5) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline and _modifiers_down():
        time.sleep(0.01)


def simulate_cmd_key(char: str) -> None:
    code = {"c": _KEY_C, "v": _KEY_V, "z": _KEY_Z}[char.lower()]
    if _has_quartz:
        try:
            src = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateCombinedSessionState)
            down = Quartz.CGEventCreateKeyboardEvent(src, code, True)
            Quartz.CGEventSetFlags(down, Quartz.kCGEventFlagMaskCommand)
            up = Quartz.CGEventCreateKeyboardEvent(src, code, False)
            Quartz.CGEventSetFlags(up, Quartz.kCGEventFlagMaskCommand)
            Quartz.CGEventPost(Quartz.kCGHIDEventTap, down)
            time.sleep(0.012)
            Quartz.CGEventPost(Quartz.kCGHIDEventTap, up)
            return
        except Exception:
            pass
    try:
        from pynput.keyboard import Controller, Key
        kb = Controller()
        with kb.pressed(Key.cmd):
            kb.press(char)
            kb.release(char)
    except Exception:
        subprocess.run(["osascript", "-e",
                        f'tell application "System Events" to keystroke "{char}" using command down'],
                       capture_output=True, timeout=1.5)


def copied_from_empty_selection() -> bool:
    """True when the last copy was an editor's "copy the whole line" fallback.

    VS Code, Cursor and other editors copy the entire current line when Cmd+C is
    pressed with nothing selected; fixing it and pasting it back would duplicate
    the line. Chromium-based editors keep their metadata in web custom data."""
    if not _has_appkit:
        return False
    import richtext
    try:
        pb = _pb()
        for t in ("vscode-editor-data", "org.chromium.web-custom-data"):
            data = pb.dataForType_(t)
            if data is not None and richtext.is_line_copy(bytes(data)):
                return True
    except Exception:
        pass
    return False


def copy_selection(timeout: float = 0.8) -> bool:
    """Cmd+C and wait for the pasteboard to change. False means nothing was selected."""
    before = change_count()
    simulate_cmd_key("c")
    deadline = time.time() + timeout
    while time.time() < deadline:
        time.sleep(0.015)
        if change_count() != before:
            time.sleep(0.02)
            return not copied_from_empty_selection()
    return before == -1 and bool(get_text())


def paste() -> None:
    simulate_cmd_key("v")


_KEY_LEFT, _KEY_RIGHT = 123, 124


def _post_key(code: int, flags: int = 0) -> bool:
    if not _has_quartz:
        return False
    try:
        src = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateCombinedSessionState)
        for down in (True, False):
            e = Quartz.CGEventCreateKeyboardEvent(src, code, down)
            Quartz.CGEventSetFlags(e, flags)
            Quartz.CGEventPost(Quartz.kCGHIDEventTap, e)
            time.sleep(0.012)
        return True
    except Exception:
        return False


def select_to_line_start() -> bool:
    """Nothing was selected: select from the cursor back to the start of its line
    (⌘⇧←, what the writer just typed) and copy that. False if the line is empty."""
    if not _has_quartz or not _post_key(_KEY_LEFT, Quartz.kCGEventFlagMaskCommand | Quartz.kCGEventFlagMaskShift):
        return False
    time.sleep(0.04)
    return copy_selection()


def collapse_selection() -> None:
    """→ : drop the selection and leave the cursor where the writer had it."""
    _post_key(_KEY_RIGHT)


# Backwards-compatible helpers used by older callers.
def get_clipboard() -> str:
    return get_text() or ""


def set_clipboard(text: str) -> bool:
    return set_text(text, transient=False)


def undo() -> None:
    simulate_cmd_key("z")
